let interest_with_principal_amount_and_number_of_days = [{
        // min_amount: 10000, actual start value
        min_amount: 0,
        max_amount: 25000,
        days: [{
                min_days: 0,
                max_days: 30,
                interest: 4,
                totalInterest: 0,
                totalAmount: 0,
            },
            {
                min_days: 30,
                max_days: 60,
                interest: 4.5,
                totalInterest: 0,
                totalAmount: 0,
            },
            {
                min_days: 60,
                max_days: 91,
                interest: 5.5,
                totalInterest: 0,
                totalAmount: 0,
            },
            {
                min_days: 91,
                max_days: 182,
                interest: 7.5,
                totalInterest: 0,
                totalAmount: 0,
            },
            {
                min_days: 182,
                max_days: 365,
                interest: 9,
                totalInterest: 0,
                totalAmount: 0,
            },
            {
                min_days: 365,
                max_days: 728,
                interest: 9.75,
                totalInterest: 0,
                totalAmount: 0,
            },
        ],
    },
    {
        min_amount: 25000,
        max_amount: 50000,
        days: [{
                min_days: 0,
                max_days: 30,
                interest: 5,
                totalInterest: 0,
                totalAmount: 0,
            },
            {
                min_days: 30,
                max_days: 60,
                interest: 5.5,
                totalInterest: 0,
                totalAmount: 0,
            },
            {
                min_days: 60,
                max_days: 91,
                interest: 6.5,
                totalInterest: 0,
                totalAmount: 0,
            },
            {
                min_days: 91,
                max_days: 182,
                interest: 8,
                totalInterest: 0,
                totalAmount: 0,
            },
            {
                min_days: 182,
                max_days: 365,
                interest: 9.5,
                totalInterest: 0,
                totalAmount: 0,
            },
            {
                min_days: 365,
                max_days: 728,
                interest: 10.25,
                totalInterest: 0,
                totalAmount: 0,
            },
        ],
    },
    {
        min_amount: 50000,
        max_amount: 100000,
        days: [{
                min_days: 0,
                max_days: 30,
                interest: 6,
                totalInterest: 0,
                totalAmount: 0,
            },
            {
                min_days: 30,
                max_days: 60,
                interest: 6.5,
                totalInterest: 0,
                totalAmount: 0,
            },
            {
                min_days: 60,
                max_days: 91,
                interest: 7.5,
                totalInterest: 0,
                totalAmount: 0,
            },
            {
                min_days: 91,
                max_days: 182,
                interest: 8.5,
                totalInterest: 0,
                totalAmount: 0,
            },
            {
                min_days: 182,
                max_days: 365,
                interest: 10,
                totalInterest: 0,
                totalAmount: 0,
            },
            {
                min_days: 365,
                max_days: 728,
                interest: 10.75,
                totalInterest: 0,
                totalAmount: 0,
            },
        ],
    },
    {
        min_amount: 100000,
        max_amount: 500000,
        days: [{
                min_days: 0,
                max_days: 30,
                interest: 7,
                totalInterest: 0,
                totalAmount: 0,
            },
            {
                min_days: 30,
                max_days: 60,
                interest: 7.75,
                totalInterest: 0,
                totalAmount: 0,
            },
            {
                min_days: 60,
                max_days: 91,
                interest: 8.5,
                totalInterest: 0,
                totalAmount: 0,
            },
            {
                min_days: 91,
                max_days: 182,
                interest: 9,
                totalInterest: 0,
                totalAmount: 0,
            },
            {
                min_days: 182,
                max_days: 365,
                interest: 105,
                totalInterest: 0,
                totalAmount: 0,
            },
            {
                min_days: 365,
                max_days: 728,
                interest: 11.25,
                totalInterest: 0,
                totalAmount: 0,
            },
        ],
    },
    {
        min_amount: 500000,
        max_amount: 1000000,
        days: [{
                min_days: 0,
                max_days: 30,
                interest: 8,
                totalInterest: 0,
                totalAmount: 0,
            },
            {
                min_days: 30,
                max_days: 60,
                interest: 8.5,
                totalInterest: 0,
                totalAmount: 0,
            },
            {
                min_days: 60,
                max_days: 91,
                interest: 9,
                totalInterest: 0,
                totalAmount: 0,
            },
            {
                min_days: 91,
                max_days: 182,
                interest: 9.5,
                totalInterest: 0,
                totalAmount: 0,
            },
            {
                min_days: 182,
                max_days: 365,
                interest: 10.5,
                totalInterest: 0,
                totalAmount: 0,
            },
            {
                min_days: 365,
                max_days: 728,
                interest: 11.5,
                totalInterest: 0,
                totalAmount: 0,
            },
        ],
    },
    {
        min_amount: 1000000,
        max_amount: 10000000,
        days: [{
                min_days: 0,
                max_days: 30,
                interest: 9,
                totalInterest: 0,
                totalAmount: 0,
            },
            {
                min_days: 30,
                max_days: 60,
                interest: 9.5,
                totalInterest: 0,
                totalAmount: 0,
            },
            {
                min_days: 60,
                max_days: 91,
                interest: 10,
                totalInterest: 0,
                totalAmount: 0,
            },
            {
                min_days: 91,
                max_days: 182,
                interest: 10.5,
                totalInterest: 0,
                totalAmount: 0,
            },
            {
                min_days: 182,
                max_days: 365,
                interest: 11,
                totalInterest: 0,
                totalAmount: 0,
            },
            {
                min_days: 365,
                max_days: 728,
                interest: 12,
                totalInterest: 0,
                totalAmount: 0,
            },
        ],
    },
];

module.exports = {
    interest_with_principal_amount_and_number_of_days: interest_with_principal_amount_and_number_of_days,
};